### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by mariotaku** [webosbrew/pages#4]
* Combine nav and title, add icon
* Use dark background
* Change font to improve readability

**Comment by mariotaku** [comment]
Apply for apps as well

**Comment by mariotaku** [comment]
Use icons (github/discord) for social links at the bottom

**Comment by Informatic** [comment]
I very much like the new theme. Thank you!

Here are some of my comments:
1. I am not entirely sure, but I somehow recall "old" theme having code block syntax colorization.
2. Code blocks are not turning into scrollable boxes and tend to overflow over the page like here: https://www.webosbrew.org/pages/luna-service-bus.html We probably may try adding `overflow: auto` to `pre` tags.
3. Adding anchors to headers would probably make it more useful → https://github.com/getpelican/pelican/issues/1357#issuecomment-43878232 + anchor links rendered on hover like they are on github.

**Comment by mariotaku** [comment]
Done!
